process_name: JREAST_TrainSimulator.exe
module_name: JREAST_TrainSimulator.exe
offsets:
  next_station_id: "0x112BE58"
  door_state: "0x1552440"
  current_time_seconds: "0x15354B4"
  current_time_minutes: "0x15354B8"
  current_time_hours: "0x15354BC"
  timetable_second: "0x15354DC"
  timetable_minute: "0x15354E0"
  timetable_hour: "0x15354E4"
  current_distance: "0x14CBA98"
  target_stop_distance: "0x10DFA70"
  line_path: "0xEEAB1E"
